// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_MvUt50hc1q_DQTEgQnAsLNXHNmvMp8',
    appId: '1:39225764694:web:6cbba1dd4aaa469f5584f7',
    messagingSenderId: '39225764694',
    projectId: 'e-money-2fa',
    authDomain: 'e-money-2fa.firebaseapp.com',
    storageBucket: 'e-money-2fa.firebasestorage.app',
    measurementId: 'G-DM03TS784D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftnIlqGLzF06Tri3tkcyos3DKhlA4-N4',
    appId: '1:39225764694:android:a99f423a2ebcaf085584f7',
    messagingSenderId: '39225764694',
    projectId: 'e-money-2fa',
    storageBucket: 'e-money-2fa.firebasestorage.app',
  );
}
